"""VOC → YOLO 格式转换模块 —— 对应方案第 6 节

将 PASCAL VOC XML 标注转换为 YOLO 格式（归一化中心坐标 + 宽高）。
"""

import xml.etree.ElementTree as ET
from pathlib import Path
from typing import List, Tuple, Optional
import shutil
import logging

from src.paths import DATA_ROOT, CLASS_NAME_TO_ID, CLASS_NAMES, SPLIT_DIR

logger = logging.getLogger(__name__)


def convert_voc_to_yolo(xml_path: Path, img_width: int, img_height: int) -> List[Tuple[int, float, float, float, float]]:
    """将一个 VOC XML 转换为 YOLO 格式标注列表。

    Args:
        xml_path: XML 文件路径
        img_width: 图像宽度
        img_height: 图像高度

    Returns:
        List of (class_id, x_center, y_center, width, height) 归一化坐标
    """
    tree = ET.parse(xml_path)
    root = tree.getroot()

    labels = []
    for obj in root.findall("object"):
        name = obj.findtext("name", "").strip().lower()
        if name not in CLASS_NAME_TO_ID:
            continue

        bndbox = obj.find("bndbox")
        if bndbox is None:
            continue

        xmin = float(bndbox.findtext("xmin", 0))
        ymin = float(bndbox.findtext("ymin", 0))
        xmax = float(bndbox.findtext("xmax", 0))
        ymax = float(bndbox.findtext("ymax", 0))

        # 过滤无效框
        if xmin >= xmax or ymin >= ymax:
            continue

        # 裁剪到图像范围内
        xmin = max(0, xmin)
        ymin = max(0, ymin)
        xmax = min(img_width, xmax)
        ymax = min(img_height, ymax)

        # 转为中心坐标 + 宽高，归一化
        x_center = (xmin + xmax) / 2.0 / img_width
        y_center = (ymin + ymax) / 2.0 / img_height
        width = (xmax - xmin) / img_width
        height = (ymax - ymin) / img_height

        # 过滤退化框
        if width <= 0 or height <= 0:
            continue

        class_id = CLASS_NAME_TO_ID[name]
        labels.append((class_id, x_center, y_center, width, height))

    return labels


def convert_dataset(
    image_stems: List[str],
    src_dir: Path,
    dst_img_dir: Path,
    dst_label_dir: Path,
    copy_images: bool = True,
) -> int:
    """批量转换 VOC 到 YOLO 格式。

    Args:
        image_stems: 要转换的文件 stem 列表
        src_dir: 源数据目录（包含 JPG 和 XML）
        dst_img_dir: 目标图像目录
        dst_label_dir: 目标标注目录
        copy_images: 是否复制图像（False 则创建软链接）

    Returns:
        成功转换的样本数
    """
    dst_img_dir.mkdir(parents=True, exist_ok=True)
    dst_label_dir.mkdir(parents=True, exist_ok=True)

    converted = 0
    for stem in image_stems:
        jpg_path = src_dir / f"{stem}.jpg"
        xml_path = src_dir / f"{stem}.xml"

        if not xml_path.exists():
            continue

        try:
            # 从 XML 获取真实图像尺寸
            tree = ET.parse(xml_path)
            root = tree.getroot()
            size = root.find("size")
            if size is None:
                continue
            img_w = int(size.findtext("width", 4096))
            img_h = int(size.findtext("height", 3000))
        except Exception:
            continue

        labels = convert_voc_to_yolo(xml_path, img_w, img_h)

        # 写 YOLO 标注（即使为空也写，保留负样本）
        label_path = dst_label_dir / f"{stem}.txt"
        with open(label_path, "w") as f:
            for cls_id, xc, yc, w, h in labels:
                f.write(f"{cls_id} {xc:.6f} {yc:.6f} {w:.6f} {h:.6f}\n")

        # 复制/链接图像（symlink 失败时自动回退到 copy）
        dst_img = dst_img_dir / f"{stem}.jpg"
        if jpg_path.exists() and not dst_img.exists():
            if copy_images:
                shutil.copy2(jpg_path, dst_img)
            else:
                try:
                    dst_img.symlink_to(jpg_path.resolve())
                except OSError:
                    shutil.copy2(jpg_path, dst_img)

        converted += 1

    logger.info(f"Converted {converted} samples to {dst_img_dir}")
    return converted


def create_yolo_dataset_yaml(
    train_img_dir: str,
    val_img_dir: str,
    output_path: Path,
    nc: int = 9,
) -> None:
    """生成 YOLO 格式的 dataset.yaml 配置文件。"""
    yaml_content = f"""# SteelGuard-YOLO Dataset Configuration
# Auto-generated by src/data/convert.py

path: {Path(train_img_dir).parent.as_posix()}
train: {Path(train_img_dir).name}
val: {Path(val_img_dir).name}

# Number of classes
nc: {nc}

# Class names
names:
{chr(10).join(f'  {i}: {name}' for i, name in enumerate(CLASS_NAMES))}
"""
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(yaml_content)
    logger.info(f"YOLO dataset YAML saved to {output_path}")


if __name__ == "__main__":
    import json
    logging.basicConfig(level=logging.INFO)

    # 读取划分文件，只转换有划分的数据
    from src.paths import SPLIT_DIR
    split_path = SPLIT_DIR / "train_val_split.json"
    if split_path.exists():
        with open(split_path, "r") as f:
            split = json.load(f)
        all_stems = split["train_stems"] + split["val_stems"]
        print(f"Using split file: {len(all_stems)} stems "
              f"(train={len(split['train_stems'])}, val={len(split['val_stems'])})")
    else:
        from src.data.health_check import check_jpg_xml_pairing
        all_stems, _, _ = check_jpg_xml_pairing(DATA_ROOT)
        print(f"No split file, using all {len(all_stems)} stems")

    yolo_img_dir = DATA_ROOT.parent / "train_yolo" / "images"
    yolo_label_dir = DATA_ROOT.parent / "train_yolo" / "labels"

    convert_dataset(all_stems, DATA_ROOT, yolo_img_dir, yolo_label_dir, copy_images=False)
    print(f"Done: {len(all_stems)} samples")
